### ISSUE TITLE
[Feature Request]  add "origin" Prefix to the Measurement names

### ISSUE THREAD

**Issue by toni-moreno** [adejoux/pSeriesCollector#14]
Right now he are generating these measurements from both data sources ( HMC API and also Nmon Files)

**From HMC**

- PartitionMemory
- PartitionProcessor
- PartitionVSCSIAdapters
- PartitionVirtualEthernetAdapters
- PartitionVirtualFiberChannelAdapters
- SystemFiberChannelAdapters
- SystemGenericAdapters
- SystemGenericVirtualAdapters
- SystemMemory
- SystemProcessor
- SystemSharedAdapters
- SystemSharedProcessorPool
- SystemgenericPhysicalAdapters

**From Nmon Files**

- cpu
- disks
- fiberchannel
- file
- ioadapt
- jfs
- lpar
- memory
- network
- page
- paging
- pools
- proc
- procaio
- sea
- top
- volumegroup

As we can see , names are really different  and doesn't give us inforamtion on the data source.

I propose add a origin prefix.

hmcXxxxXxxxXxxx => for HMC measurement names and 
nmonXxxxx => in the Nmon Data

@adejoux @sbengo , what do you thing about ?

**Comment by adejoux** [comment]
Hello,

I agree with this modification.

**Comment by toni-moreno** [comment]
@adejoux already done!! thank you al lot!
