### ISSUE TITLE
[Feature Request] Add feature to skip NMON Section

### ISSUE THREAD

**Issue by sbengo** [adejoux/pSeriesCollector#33]
It would be great to add a new field to let the user skip some NMON entire sections. It could be a regex and based on the NMON entries

Example:

![image](https://user-images.githubusercontent.com/13196237/50829403-b5c80800-1344-11e9-93c7-3d027d240672.png)

**Comment by toni-moreno** [comment]
Implemented in 0.5.2 as an comma separated Regex value, with a little restriction : the regex itself will not be able to work with commas )
